[package]
name = "PaymentSplitter"
version = "1.0.0"

[addresses]
payment_splitter = "0x5056e52fedf1506497b6e811e4341bb18e4369f039bb448dcb51f771a8c9f9ea"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"